controller_frequency: 1

TrajectoryPlannerROS:
  max_vel_x: 0.50 #0.5
  min_vel_x: -0.1 #0.01
  max_vel_theta: 1.57 #1.5

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0
  
  yaw_goal_tolerance: 0.01
  xy_goal_tolerance: 0.1

  sim_time: 100
  sim_granularity: 0.010

  vx_samples: 20.0
  vtheta_samples: 40.0

  pdist_scale: 5.0
  gdist_scale : 0.2
  occdist_scale: 0.03

  holonomic_robot: false

  
